<a href="https://colab.research.google.com/github/DELTAREET/SIT/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
## Numpy


# creating 0-d array using numpy
import numpy as np
zeroDimensionArray = np.array(100)
print("This is my 0-d array")
print(zeroDimensionArray)
print("The dimension of this array is ",zeroDimensionArray.ndim)


This is my 0-d array
100
The dimension of this array is  0


In [12]:
# creating 1-d array
import numpy as np
oneDimensionArray = np.array([1,2,3,4,5])
print("This is mmy 1-d array")
print(oneDimensionArray)
print("The dimension of this array is ",oneDimensionArray.ndim)
print("The first element present in this array ",oneDimensionArray[0])
print("The third element present in this array ",oneDimensionArray[2])
print("The sum of the element present inthe 2nd and 3rd index is ",oneDimensionArray[2] + oneDimensionArray[3])

This is mmy 1-d array
[1 2 3 4 5]
The dimension of this array is  1
The first element present in this array  1
The third element present in this array  3
The sum of the element present inthe 2nd and 3rd index is  7


In [17]:
# creating 2-d array
import numpy as np
twoDimensionArray = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("This is my 2-d array")
print(twoDimensionArray)
print("The dimension of this array is ",twoDimensionArray.ndim)
print("Displaying 1st row : ",twoDimensionArray[0])
print("Displaying 2nd row : ",twoDimensionArray[1])
print("Displaying 1st element of the first row ",twoDimensionArray[0,0])
print("Displaying 3rd element of the second row ",twoDimensionArray[1,3])
print("The sum of the element present in the first row 2nd index and second row 3rd index is ",twoDimensionArray[0,4] + twoDimensionArray[1,3])


This is my 2-d array
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
The dimension of this array is  2
Displaying 1st row :  [1 2 3 4 5]
Displaying 2nd row :  [ 6  7  8  9 10]
Displaying 1st element of the first row  1
Displaying 3rd element of the second row  9
The sum of the element present in the first row 2nd index and second row 3rd index is  14


In [18]:
#creating 3-d Array
import numpy as np
threeDimensionArray = np.array([[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]])
print("This is my 3-d array")
print(threeDimensionArray)
print("The dimension of this array is ",threeDimensionArray.ndim)
print("Displaying the first row of this array ",threeDimensionArray[0,0])
print("Displaying the third row of this array ",threeDimensionArray[0,2])
print("Displaying seacond element of the third row ",threeDimensionArray[0,2,1])



This is my 3-d array
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]
The dimension of this array is  3
Displaying the first row of this array  [1 2 3 4 5]
Displaying the third row of this array  [11 12 13 14 15]
Displaying seacond element of the third row  12


In [26]:
# Array Slicing
import numpy as np
oneDimensionArray = np.array([1,2,3,4,5,6,7,8,9,10])
print("This is mmy 1-d array")
print("your array is : ")
print(oneDimensionArray)
print("The dimension of this array is ",oneDimensionArray.ndim)
print("The dimension of this array is : ",oneDimensionArray)
print("Displaying element from 3rd to 6th index ",oneDimensionArray[3:7])
print("Displaying element after 5th element of this array ",oneDimensionArray[5:])
print("Displaying element before 5th element of this array ",oneDimensionArray[:5])



This is mmy 1-d array
your array is : 
[ 1  2  3  4  5  6  7  8  9 10]
The dimension of this array is  1
The dimension of this array is :  [ 1  2  3  4  5  6  7  8  9 10]
Displaying element from 3rd to 6th index  [4 5 6 7]
Displaying element after 5th element of this array  [ 6  7  8  9 10]
Displaying element before 5th element of this array  [1 2 3 4 5]


In [ ]:
#copy and view
import numpy as np
OriginalArray = np.arrayy([1,2,3,4])
CopiedArray = OriginalArray.copy()
