<a href="https://colab.research.google.com/github/DELTAREET/SIT/blob/main/training%20(ML)-1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
## Numpy


# creating 0-d array using numpy
import numpy as np
zeroDimensionArray = np.array(100)
print("This is my 0-d array")
print(zeroDimensionArray)
print("The dimension of this array is ",zeroDimensionArray.ndim)


This is my 0-d array
100
The dimension of this array is  0


In [12]:
# creating 1-d array
import numpy as np
oneDimensionArray = np.array([1,2,3,4,5])
print("This is mmy 1-d array")
print(oneDimensionArray)
print("The dimension of this array is ",oneDimensionArray.ndim)
print("The first element present in this array ",oneDimensionArray[0])
print("The third element present in this array ",oneDimensionArray[2])
print("The sum of the element present inthe 2nd and 3rd index is ",oneDimensionArray[2] + oneDimensionArray[3])

This is mmy 1-d array
[1 2 3 4 5]
The dimension of this array is  1
The first element present in this array  1
The third element present in this array  3
The sum of the element present inthe 2nd and 3rd index is  7


In [17]:
# creating 2-d array
import numpy as np
twoDimensionArray = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("This is my 2-d array")
print(twoDimensionArray)
print("The dimension of this array is ",twoDimensionArray.ndim)
print("Displaying 1st row : ",twoDimensionArray[0])
print("Displaying 2nd row : ",twoDimensionArray[1])
print("Displaying 1st element of the first row ",twoDimensionArray[0,0])
print("Displaying 3rd element of the second row ",twoDimensionArray[1,3])
print("The sum of the element present in the first row 2nd index and second row 3rd index is ",twoDimensionArray[0,4] + twoDimensionArray[1,3])


This is my 2-d array
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
The dimension of this array is  2
Displaying 1st row :  [1 2 3 4 5]
Displaying 2nd row :  [ 6  7  8  9 10]
Displaying 1st element of the first row  1
Displaying 3rd element of the second row  9
The sum of the element present in the first row 2nd index and second row 3rd index is  14


In [18]:
#creating 3-d Array
import numpy as np
threeDimensionArray = np.array([[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]])
print("This is my 3-d array")
print(threeDimensionArray)
print("The dimension of this array is ",threeDimensionArray.ndim)
print("Displaying the first row of this array ",threeDimensionArray[0,0])
print("Displaying the third row of this array ",threeDimensionArray[0,2])
print("Displaying seacond element of the third row ",threeDimensionArray[0,2,1])



This is my 3-d array
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]
The dimension of this array is  3
Displaying the first row of this array  [1 2 3 4 5]
Displaying the third row of this array  [11 12 13 14 15]
Displaying seacond element of the third row  12


In [26]:
# Array Slicing
import numpy as np
oneDimensionArray = np.array([1,2,3,4,5,6,7,8,9,10])
print("This is mmy 1-d array")
print("your array is : ")
print(oneDimensionArray)
print("The dimension of this array is ",oneDimensionArray.ndim)
print("The dimension of this array is : ",oneDimensionArray)
print("Displaying element from 3rd to 6th index ",oneDimensionArray[3:7])
print("Displaying element after 5th element of this array ",oneDimensionArray[5:])
print("Displaying element before 5th element of this array ",oneDimensionArray[:5])



This is mmy 1-d array
your array is : 
[ 1  2  3  4  5  6  7  8  9 10]
The dimension of this array is  1
The dimension of this array is :  [ 1  2  3  4  5  6  7  8  9 10]
Displaying element from 3rd to 6th index  [4 5 6 7]
Displaying element after 5th element of this array  [ 6  7  8  9 10]
Displaying element before 5th element of this array  [1 2 3 4 5]


In [5]:
#copy and view
import numpy as np
OriginalArray = np.array([1,2,3,4])
CopiedArray = OriginalArray.copy()
print("Original Array : ", OriginalArray)
OriginalArray[2] = 100
print("Original Array : ",OriginalArray)
CopiedArray[0] = 600
print("Copied Array : ", CopiedArray)

Original Array :  [1 2 3 4]
Original Array :  [  1   2 100   4]
Copied Array :  [600   2   3   4]


In [4]:
#copy and view
import numpy as np
OriginalArray = np.array([1,2,3,4])
CopiedArray = OriginalArray.view()
print("This is the Original Array : ",OriginalArray)
print("Changes Applying to original array : ")
OriginalArray[2] = 121
print("this is the Original Array : ",OriginalArray)
print("This is the Copied Array : ", CopiedArray)

This is the Original Array :  [1 2 3 4]
Changes Applying to original array : 
this is the Original Array :  [  1   2 121   4]
This is the Copied Array :  [  1   2 121   4]


# New Section 1

In [1]:
# creating 0-d array using numpy
import numpy as np
zeroDimensionArray = np.array(100)
print("This is my 0-d array")
print(zeroDimensionArray)
print("The dimension of this array is ",zeroDimensionArray.ndim)

This is my 0-d array
100
The dimension of this array is  0


In [5]:
# creating 1-d array
import numpy as np
oneDimensionArray = np.array([1,2,3,4,5])
print("This is my 1-d array")
print(oneDimensionArray)
print("The dimension of this array is ",oneDimensionArray.ndim)


This is my 1-d array
[1 2 3 4 5]
The dimension of this array is  1


In [4]:
# creating 6-d array
import numpy as np
sixDimensionArray = np.array([[[[[[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]]]]]])
print("This is my 6-d array")
print(sixDimensionArray)
print("This dimension of this array is ",sixDimensionArray.ndim)

This is my 6-d array
[[[[[[ 1  2  3]
     [ 4  5  6]
     [ 7  8  9]
     [10 11 12]
     [13 14 15]
     [16 17 18]]]]]]
This dimension of this array is  6


In [7]:
# creating 1-d array
import numpy as np
oneDimensionArray = np.array([1,2,3,4,5])
print("This is my 1-d array")
print(oneDimensionArray)
print("The dimension of this array is ",oneDimensionArray.ndim)

print("The sum of the element present in the second and fourth index is ",oneDimensionArray[1] + oneDimensionArray[3])

This is my 1-d array
[1 2 3 4 5]
The dimension of this array is  1
The sum of the element present in the second and fourth index is  6


In [8]:
# creating 2-d array
import numpy as np
twoDimensionArray = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("This is my 2-d array")
print(twoDimensionArray)
print("Displaying 3rd element of the first row ",twoDimensionArray[0,2])
print("Displaying 2nd element of the second row ",twoDimensionArray[1,1])

This is my 2-d array
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Displaying 3rd element of the first row  3
Displaying 2nd element of the second row  7


In [14]:
#creating 3-d Array
import numpy as np
threeDimensionArray = np.array([[[1,2,3,],[4,5,6],[7,8,9]]])
print(threeDimensionArray)
print("the sum of the 3rd element of the 1st row & 3rd elementof the 2nd row & 3rd element of 3rd row:",threeDimensionArray[0,0,2]+threeDimensionArray[0,1,2]+threeDimensionArray[0,2,2])

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
the sum of the 3rd element of the 1st row & 3rd elementof the 2nd row & 3rd element of 3rd row: 18


In [15]:
#creating 2-d array

import numpy as np
twoDimensionArray = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("This is my 2-d array")
print(twoDimensionArray*2)

This is my 2-d array
[[ 2  4  6  8 10]
 [12 14 16 18 20]]


In [17]:
# Array slicing

import numpy as np
oneDimensionArray = np.array([28,55,67,89,100,125,532])

print("Your array is :")
print(oneDimensionArray)
print("The dimension of this array is :",oneDimensionArray.ndim)
print("displaying element from 2nd to the index",oneDimensionArray[2:5])
print("displaying all element after 5th element of this array",oneDimensionArray[2:])
print("displaying all element before 5th element of this array",oneDimensionArray[:5])

Your array is :
[ 28  55  67  89 100 125 532]
The dimension of this array is : 1
displaying element from 2nd to the index [ 67  89 100]
displaying all element after 5th element of this array [ 67  89 100 125 532]
displaying all element before 5th element of this array [ 28  55  67  89 100]


In [18]:
#creating 2-d array

import numpy as np
twoDimensionArray = np.array([[1,2,3,4,5,6,7,8],[9,10,11,12,13,14,15,16]])
print("This is my 2-d array")
print(twoDimensionArray)
print("The dimension of this array is :",twoDimensionArray.ndim)
print("displaying element from 3rd to 6th index",twoDimensionArray[0,3:7])
print("displaying all element after 5th element of this array",twoDimensionArray[1,:5])

This is my 2-d array
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]
The dimension of this array is : 2
displaying element from 3rd to 6th index [3 4 5 6]
displaying all element after 5th element of this array [ 9 10 11 12 13]


In [19]:
import numpy as np
realArray = np.array([10,9,8,7,6])
duplicateArray = realArray.copy()
print("This is the real Array:",realArray)
print("This is the duplicate Array:",duplicateArray)
duplicateArray[2] = 12
print("This is the real Array:",realArray)
print("This is the duplicate Array:",duplicateArray)

This is the real Array: [10  9  8  7  6]
This is the duplicate Array: [10  9  8  7  6]
This is the real Array: [10  9  8  7  6]
This is the duplicate Array: [10  9 12  7  6]


In [1]:
# 
import numpy as np
oneDimensionArray = np.array([1,2,3,4,5])
for i in oneDimensionArray:
  print(i)

1
2
3
4
5


In [6]:
#numpy iteration for 2-d array
import numpy as np
twoDimensionArray = np.array([[1,2],[3,4]])
for i in twoDimensionArray:
    print(i)

[1 2]
[3 4]


In [7]:
#numpy iteration for 2-d array
import numpy as np
twoDimensionArray = np.array([[1,2],[3,4]])
for i in twoDimensionArray:
  for j in i:
    print(j)

1
2
3
4


In [8]:
#numpy iterration for 3-d array
import numpy as np
threeDimensionArray = np.array([[[1,2],[3,4],[5,6]]])
for i in threeDimensionArray:
  for j in i:
    for k in j:
      print(k)

1
2
3
4
5
6


In [9]:
#numpy iterrationusing nditer() function
import numpy as np
threeDimensionalArray = np.array([[[1,2],[3,4],[5,6]]])
for i in np.nditer(threeDimensionalArray):
  print(i)

1
2
3
4
5
6


In [11]:
# Numpy Joins (Join 1-d array) using concatenate() function
import numpy as np
firstArray = np.array([1,2])
print("This is the first array : ",firstArray)
secondArray = np.array([3,4])
print("This is the second array : ",secondArray)
print("After joining two array: ",np.concatenate((firstArray,secondArray)))

This is the first array :  [1 2]
This is the second array :  [3 4]
After joining two array:  [1 2 3 4]


In [13]:
# Numpy Joins (Join 2-d array) using concatenate() function
import numpy as np
firstArray = np.array([[1,2],[3,4]])
print("This is the first array : \n",firstArray)
secondArray = np.array([[5,6],[7,8]])
print("This is the second array : \n",secondArray)
print("After joining two array :\n",np.concatenate((firstArray, secondArray),axis=1))

This is the first array : 
 [[1 2]
 [3 4]]
This is the second array : 
 [[5 6]
 [7 8]]
After joining two array :
 [[1 2 5 6]
 [3 4 7 8]]


In [14]:
# Numpy Joins (Join 2-d array) using concatenate() function in axis = 0
import numpy as np
firstArray = np.array([[1,2],[3,4]])
print("This is the first array : \n",firstArray)
secondArray = np.array([[5,6],[7,8]])
print("This is the second array : \n",secondArray)
print("After joining two array :\n",np.concatenate((firstArray, secondArray),axis=0))

This is the first array : 
 [[1 2]
 [3 4]]
This is the second array : 
 [[5 6]
 [7 8]]
After joining two array :
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [17]:
#numpy joins using stack() function
import numpy as np
firstArray =np.array([1,11,111])
print("First Array = ",firstArray)
secondArray = np.array([2,22,222])
print("Second Array = ",secondArray)
print("After Joining two array : \n",np.stack((firstArray, secondArray)))

First Array =  [  1  11 111]
Second Array =  [  2  22 222]
After Joining two array : 
 [[  1  11 111]
 [  2  22 222]]


In [18]:
#numpy joins using stack() function [axis = 1]
import numpy as np
firstArray =np.array([1,11,111])
print("First Array = ",firstArray)
secondArray = np.array([2,22,222])
print("Second Array = ",secondArray)
print("After Joining two array : \n",np.stack((firstArray, secondArray),axis=1))

First Array =  [  1  11 111]
Second Array =  [  2  22 222]
After Joining two array : 
 [[  1   2]
 [ 11  22]
 [111 222]]


In [21]:
#numpy joins using stack() function
import numpy as np
firstArray =np.array([1,2,3])
print("The first Array is = ",firstArray)
secondArray = np.array([4,5,6])
print("The second Array is = ",secondArray)
print("After Joining two array : ",np.hstack((firstArray, secondArray)))

The first Array is =  [1 2 3]
The second Array is =  [4 5 6]
After Joining two array :  [1 2 3 4 5 6]


In [25]:
# Numpy Splitting
import numpy as np
array = np.array([1,2,3,4,5,6,7,8,9,10])
print("the array is : ",array)
#splitting array into 3 parts
print("After Splitting : ",np.array_split(array, 3))

the array is :  [ 1  2  3  4  5  6  7  8  9 10]
After Splitting :  [array([1, 2, 3, 4]), array([5, 6, 7]), array([ 8,  9, 10])]


In [26]:
#numpy search
import numpy as np
array = np.array([1,2,3,4,4,5,6,4])
print("The array is : ",array)
# find all the index where value = 4 exists
var = np.where(array == 4)
print(var)

The array is :  [1 2 3 4 4 5 6 4]
(array([3, 4, 7]),)


In [27]:
 #numpy search
import numpy as np
array = np.array([1,2,3,6,11,12,27])
print("The array is : ",array)
# find all the index where value is divisible by 3 exits
var = np.where(array % 3 == 0)
print(var)

The array is :  [ 1  2  3  6 11 12 27]
(array([2, 3, 5, 6]),)


In [ ]:
# Numpy sorting
import numpy as np
arr=np.array([1,5,6,2,5,8,43,12,32])
print("This is the Array:\n",arr)
print("After sorting the array:\n",np.sort(arr))